export interface Casino {
  id: number;
  name: string;
  province: string;
  type: 'online' | 'land-based';
  rating: number;
  description: string;
  features: string[];
  bonus: string;
  color: string;
  url: string;
  badges: string[];
}

export const casinos: Casino[] = [
  {
    id: 1,
    name: 'Jackpot City Casino',
    province: 'Ontario',
    type: 'online',
    rating: 4.8,
    description: 'One of Canada\'s most trusted online casinos since 1998, offering 500+ games, fast payouts, and a generous welcome package.',
    features: ['500+ Slots & Table Games', 'Live Dealer Lobby', 'Interac & e-Transfer'],
    bonus: '$1,600 Welcome Bonus',
    color: 'bg-yellow-600',
    url: 'https://www.jackpotcity.com/',
    badges: ["Editor's Pick", 'Top Bonus'],
  },
  {
    id: 2,
    name: 'Spin Casino',
    province: 'British Columbia',
    type: 'online',
    rating: 4.7,
    description: 'Premium slots and live casino experience with Microgaming-powered titles and a stellar loyalty programme for Canadian players.',
    features: ['600+ Microgaming Slots', 'VIP Loyalty Rewards', 'Mobile Optimised'],
    bonus: '$1,000 Welcome Bonus',
    color: 'bg-purple-700',
    url: 'https://www.spincasino.com/',
    badges: ['Top Rated'],
  },
  {
    id: 3,
    name: 'Zodiac Casino',
    province: 'Quebec',
    type: 'online',
    rating: 4.6,
    description: 'Famous for its $1 deposit to win $20 free spins offer. Powered by Microgaming with consistent payouts and responsive support.',
    features: ['$1 Deposit Offer', '500+ Games', '24/7 Live Chat'],
    bonus: '80 Free Spins for $1',
    color: 'bg-indigo-700',
    url: 'https://www.zodiac-casino.com/',
    badges: ['Best Value'],
  },
  {
    id: 4,
    name: 'Ruby Fortune Casino',
    province: 'Alberta',
    type: 'online',
    rating: 4.5,
    description: 'Elegant casino offering a rich Ruby-themed experience, backed by eCOGRA certification and reliable Canadian banking options.',
    features: ['eCOGRA Certified', 'Fast Withdrawals', 'Loyalty Points'],
    bonus: '$750 Welcome Bonus',
    color: 'bg-red-700',
    url: 'https://www.rubyfortune.com/',
    badges: ['Trusted'],
  },
  {
    id: 5,
    name: 'Mummy\'s Gold Casino',
    province: 'Manitoba',
    type: 'online',
    rating: 4.4,
    description: 'Egyptian-themed online casino with a huge game library, weekly tournaments, and excellent customer support for Canadian players.',
    features: ['Weekly Tournaments', '400+ Games', 'Email & Chat Support'],
    bonus: '$500 Welcome Bonus',
    color: 'bg-amber-700',
    url: 'https://www.mummysgold.com/',
    badges: ['Fan Favourite'],
  },
  {
    id: 6,
    name: 'Royal Vegas Casino',
    province: 'Ontario',
    type: 'online',
    rating: 4.6,
    description: 'A regal online casino experience with a massive game library, progressive jackpots, and an industry-leading VIP programme.',
    features: ['Progressive Jackpots', 'VIP Programme', 'Interac Deposits'],
    bonus: '$1,200 Welcome Bonus',
    color: 'bg-blue-800',
    url: 'https://www.royalvegas.com/',
    badges: ["Editor's Pick"],
  },
  {
    id: 7,
    name: 'Casino Niagara',
    province: 'Ontario',
    type: 'land-based',
    rating: 4.3,
    description: 'Located steps from the iconic Niagara Falls, this vibrant casino features over 1,300 slot machines and 40 table games.',
    features: ['1,300+ Slots', '40 Table Games', 'Niagara Falls Views'],
    bonus: 'Free Play Fridays',
    color: 'bg-teal-700',
    url: 'https://www.fallsviewcasinoresort.com/',
    badges: ['Landmark'],
  },
  {
    id: 8,
    name: 'Fallsview Casino Resort',
    province: 'Ontario',
    type: 'land-based',
    rating: 4.7,
    description: 'Canada\'s premier resort casino perched above Niagara Falls with luxury hotel rooms, world-class dining, and live entertainment.',
    features: ['3,000+ Slot Machines', 'Live Entertainment', '5-Star Hotel'],
    bonus: 'Members Rewards Club',
    color: 'bg-emerald-800',
    url: 'https://www.fallsviewcasinoresort.com/',
    badges: ['Luxury', 'Top Rated'],
  },
  {
    id: 9,
    name: 'Grey Eagle Resort & Casino',
    province: 'Alberta',
    type: 'land-based',
    rating: 4.5,
    description: 'Calgary\'s largest casino and entertainment complex featuring 1,100 slots, 45 table games, live music, and outstanding dining.',
    features: ['1,100 Slots', 'Live Music Venue', 'Fine Dining'],
    bonus: 'Players Club Points',
    color: 'bg-stone-700',
    url: 'https://www.greyeagleresortandcasino.ca/',
    badges: ['Best in Alberta'],
  },
  {
    id: 10,
    name: 'River Rock Casino Resort',
    province: 'British Columbia',
    type: 'land-based',
    rating: 4.4,
    description: 'Richmond\'s award-winning resort casino on the Fraser River featuring 1,000+ slots, poker room, and a luxury hotel.',
    features: ['1,000+ Slots', 'Poker Room', 'Fraser River Views'],
    bonus: 'Encore Rewards',
    color: 'bg-cyan-800',
    url: 'https://www.riverrock.com/',
    badges: ['Best in BC'],
  },
  {
    id: 11,
    name: 'Playzee Casino',
    province: 'British Columbia',
    type: 'online',
    rating: 4.3,
    description: 'Fun and colourful online casino with a quirky theme, tons of slots, and a generous welcome offer popular with Canadian players.',
    features: ['2,000+ Games', 'Weekend Reload Bonus', 'Quick Payout'],
    bonus: '$300 + 200 Free Spins',
    color: 'bg-pink-700',
    url: 'https://www.playzee.com/',
    badges: ['Most Fun'],
  },
  {
    id: 12,
    name: '888 Casino Canada',
    province: 'Quebec',
    type: 'online',
    rating: 4.5,
    description: 'Global powerhouse offering a stellar online casino experience in Canada with renowned reliability, huge game selection, and live tables.',
    features: ['Live Casino Tables', 'Mobile App', 'Instant Play'],
    bonus: '$200 Welcome Bonus',
    color: 'bg-orange-700',
    url: 'https://www.888casino.com/',
    badges: ['Global Brand'],
  },
];
