export interface Hotel {
  id: number;
  name: string;
  province: string;
  category: 'Casino Resort' | 'Luxury' | 'Budget';
  rating: number;
  amenities: string[];
  priceRange: string;
  description: string;
  url: string;
  color: string;
}

export const hotels: Hotel[] = [
  {
    id: 1,
    name: 'Fallsview Casino Resort Hotel',
    province: 'Ontario',
    category: 'Casino Resort',
    rating: 4.8,
    amenities: ['Spa & Wellness', 'Fine Dining', 'Indoor Pool', 'Casino Access', 'Conference Centre'],
    priceRange: '$$$$$',
    description: 'Overlooking the majestic Niagara Falls, this world-class resort combines luxury accommodation with one of Canada\'s best casinos under one roof.',
    url: 'https://www.fallsviewcasinoresort.com/',
    color: 'bg-emerald-600',
  },
  {
    id: 2,
    name: 'River Rock Casino Resort',
    province: 'British Columbia',
    category: 'Casino Resort',
    rating: 4.5,
    amenities: ['Casino Floor', 'Spa', 'Multiple Restaurants', 'Event Centre', 'Valet Parking'],
    priceRange: '$$$$',
    description: 'Award-winning resort on the Fraser River in Richmond offering a full casino, gourmet dining options, and elegantly appointed rooms.',
    url: 'https://www.riverrock.com/',
    color: 'bg-blue-700',
  },
  {
    id: 3,
    name: 'Grey Eagle Resort & Casino',
    province: 'Alberta',
    category: 'Casino Resort',
    rating: 4.5,
    amenities: ['Casino Access', 'Live Entertainment', 'Steakhouse', 'Sports Bar', 'Gift Shop'],
    priceRange: '$$$',
    description: 'Calgary\'s largest entertainment complex blending First Nations culture with world-class gaming, dining, and live concert experiences.',
    url: 'https://www.greyeagleresortandcasino.ca/',
    color: 'bg-amber-700',
  },
  {
    id: 4,
    name: 'Fairmont Chateau Lake Louise',
    province: 'Alberta',
    category: 'Luxury',
    rating: 4.9,
    amenities: ['Mountain Views', 'Ski Access', 'Fine Dining', 'Spa', 'Concierge Service'],
    priceRange: '$$$$$',
    description: 'The "Diamond in the Wilderness" — an iconic Fairmont property nestled in the Canadian Rockies on the shore of the stunning Lake Louise.',
    url: 'https://www.fairmont.com/lake-louise/',
    color: 'bg-sky-700',
  },
  {
    id: 5,
    name: 'The Ritz-Carlton Toronto',
    province: 'Ontario',
    category: 'Luxury',
    rating: 4.8,
    amenities: ['Rooftop Pool', 'Spa', 'Michelin Dining', 'Fitness Centre', 'Concierge'],
    priceRange: '$$$$$',
    description: 'Toronto\'s most prestigious address, steps from the financial district, offering impeccable service, lavish suites, and a world-class spa.',
    url: 'https://www.ritzcarlton.com/toronto',
    color: 'bg-slate-700',
  },
  {
    id: 6,
    name: 'Hotel Le Germain Montreal',
    province: 'Quebec',
    category: 'Luxury',
    rating: 4.7,
    amenities: ['Rooftop Terrace', 'Gourmet Breakfast', 'Fitness Centre', 'Bilingual Staff', 'City Views'],
    priceRange: '$$$$',
    description: 'A boutique luxury hotel in the heart of Old Montreal, famed for its chic design, personalised service, and prime location near Old Port.',
    url: 'https://www.germainhotels.com/en/hotel-le-germain/montreal',
    color: 'bg-rose-700',
  },
  {
    id: 7,
    name: 'Sandman Hotel Calgary City Centre',
    province: 'Alberta',
    category: 'Budget',
    rating: 4.0,
    amenities: ['Free Parking', 'Restaurant', 'Fitness Room', 'Pet Friendly', 'Business Centre'],
    priceRange: '$$',
    description: 'A solid mid-range option in downtown Calgary offering comfortable rooms, free parking, and easy access to Stampede Park and attractions.',
    url: 'https://www.sandmanhotels.com/calgary-city-centre',
    color: 'bg-green-700',
  },
  {
    id: 8,
    name: 'Holiday Inn Express Vancouver Airport',
    province: 'British Columbia',
    category: 'Budget',
    rating: 3.9,
    amenities: ['Free Shuttle', 'Hot Breakfast', 'Pool', 'Fitness Centre', 'Free WiFi'],
    priceRange: '$$',
    description: 'Great value accommodation near YVR airport with complimentary shuttle service, hot breakfast included, and clean modern rooms.',
    url: 'https://www.ihg.com/holidayinnexpress/hotels/us/en/richmond/yvrra/hoteldetail',
    color: 'bg-orange-600',
  },
  {
    id: 9,
    name: 'Westin Harbour Castle Toronto',
    province: 'Ontario',
    category: 'Luxury',
    rating: 4.6,
    amenities: ['Lake Views', 'Indoor Pool', 'Spa', 'Marina Access', 'Multiple Restaurants'],
    priceRange: '$$$$',
    description: 'Toronto\'s waterfront gem offering panoramic views of Lake Ontario, world-class amenities, and direct access to the CN Tower district.',
    url: 'https://www.marriott.com/westin-harbour-castle-toronto',
    color: 'bg-violet-700',
  },
  {
    id: 10,
    name: 'Casino du Lac-Leamy Hotel',
    province: 'Quebec',
    category: 'Casino Resort',
    rating: 4.4,
    amenities: ['Casino Access', 'Spa Nordik', 'Gourmet Dining', 'Meeting Rooms', 'Shuttle'],
    priceRange: '$$$',
    description: 'Part of the award-winning Lac-Leamy complex in Gatineau, just minutes from Ottawa, offering luxury rooms and a world-class casino.',
    url: 'https://www.casinodulaclamy.com/',
    color: 'bg-teal-700',
  },
];
